contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #subspeciesprofiler channel"
    url: https://github.com/ebi-metagenomics/subspeciesprofiler/issues
    about: Discussion about the ebi-metagenomics/subspeciesprofiler pipeline
